# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/postgresql.cnpg.io/backup_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
  name: cnpg-smoke-restored
  labels:
    cnpg.io/cluster: &cluster cnpg-smoke-pg
spec:
  cluster:
    name: *cluster
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
