# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &app external-dns-cloudflare
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: external-dns-cloudflare-secret
    creationPolicy: Owner
  data:
    - secretKey: CF_API_TOKEN
      remoteRef:
        key: *app
        property: CF_API_TOKEN
