# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/tailscale.com/proxyclass_v1alpha1.json
apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  name: tailscale-ingress
spec:
  statefulSet:
    pod:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
      tailscaleContainer:
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop: [ALL]
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            memory: 256Mi
