apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:UcsUpKjsvdDV14MTPG0fFwIiZ87O3vu+diXXD4Ofc38=,iv:g5eD3RrX3U4J7cxeQYa9pqkQdd/WL5EoABmHv4/f8cA=,tag:DZLAbCRrmMfy0jge4MS0pA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yefuafglgmxqztx50yt6ts2a2z9tg48ywnhgrz4zxlqh5w6xvqqqr22agq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGYVRYUVAvcUZkTDFRcVR3
            b0RMVjhZVWF3ait5NUxyYWFJVkdkazNuQ25JCnFqRzZyNTJPOUxRYmQxMURQREFo
            N3FNMW00d3ZnTFJoYWw4dnNFLzNvaGcKLS0tIDJEeHRqSE1oZG1hNWU3WitLTFJi
            bkN4aWdkdlRObkgwWVRqZS8wODhwd0EK/MWW8W5EH/JGYpF2rqQFgukux5iDlZE2
            9Rsrfxn9nXP9NO8Sw0luFYz1DF5QCMVtLSf4/UBVg9TL/RQOH6FCig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-17T05:01:30Z"
    mac: ENC[AES256_GCM,data:OkCwxffAsP3gUjI+NVm1qDqNjzkbfdXYDgctxpx9dPl8cAsED/P9lw2A9nx59qZvPD60ojzskNuEw7H7TAOMvydmPeg27ddtO5iDAKfWISYg33hjF8S8CseMcjU4C4H25fboXr7u9EekTSFahSexgVRdmhaMBL45URoBwaAG+V8=,iv:yNqXRBaxSu2K1Mc3L7FRB6gWJKnSkmHlyb36SqYjCqg=,tag:7aoP6UWTTsj5KAvC0MDdOw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
