---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - namespace.yaml
  # Apps
  - teslamate/ks.yaml
  - teslamate/ks-restore.yaml
  # - paperless/ks.yaml
