apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:kTAlinomjg==,iv:WiIrhfD0h5VHrZCjIPEcCkBsnGa35tcWQBRDUcb6n4w=,tag:jRfXf+FdWbVwf4kyCuPtwQ==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:aHL+k39FALa9Rv65cA==,iv:5KKhhZYhL+IYuem5U/Lm5kFr8JaWcHCI0jUIXq1vqpw=,tag:1mQ2SmNe292KfP5it1W4TA==,type:str]
    SECRET_CLOUDFLARE_ACCOUNT_ID: ENC[AES256_GCM,data:nvUa43+KwUGZAGwiMubnwoR89y/XuDcDuJZAOR/I3kg=,iv:F+1on46p7ZkANI+QEdfmwQ94UjmA/DUAsoWTN1s2fi4=,tag:SjhAitwCKGpfe/M4TvzTSA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:psuN/LNAc+apMA==,iv:f1qS3I33jg0xCfJOgigOmh+iymKcEpw3czI1rlR2YFw=,tag:luuB7JWI10yFSZunYdruuA==,type:str]
    SECRET_TAILSCALE_DOMAIN: ENC[AES256_GCM,data:lK0G3kzh+HsEjNCYs6Zp2Ra2cQ==,iv:dQqdDei0UEin5R3I2pSZt1nJhW7Jm9GNlPCjS7FZ21s=,tag:gl/PXN+mp8uXZYa414Ktyg==,type:str]
sops:
    age:
        - recipient: age1yefuafglgmxqztx50yt6ts2a2z9tg48ywnhgrz4zxlqh5w6xvqqqr22agq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvTWxXdTdNei9TZXV2dmNR
            V24yVjZBQ2ZzNS9MbFJza3V0T3hsVmFnWjBzClVPZE9waXp1QWVRS08vRkgvYitN
            SkZ4SUpKYytKM1JacGk4L3E1ZEppaEUKLS0tIG41RWVGVytuZENKdWNxbmlUUWcx
            YXpyYndKWndDRzBVb09Sd0ZsQmZFOE0K22x3EjQ1mnY1e9uadBa2o03JjJmKwpq/
            DKF48Snek+TdvojsLQPhugNW5icWhxx+gxz7LCSqYhnltWRGHVxslw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-07T21:25:43Z"
    mac: ENC[AES256_GCM,data:jehl0P6rwdA8bIgr4NB4idmfvUo3WmHkK2tz1pel2ZxF1b+t//OR8Luq5S1IYpovfcBaGQOQjjS/9gWUNqBFr6hTL79u6ui6a0gGrOfAJ4Tn2dThs4xt1+GcLoaSEZE8a2eaAjjHDjL3gnZO8YnabvctpsbSmze3KP6+KdvDOF8=,iv:1vCnmed43U4FsW2SA1XM55RTa6rldEz07Y8iIkttOgQ=,tag:/feX4DG85mH6xPTjcuxJKg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
