apiVersion: v1
kind: Secret
metadata:
    name: pihole-secret
stringData:
    ADMIN_PASSWORD: ENC[AES256_GCM,data:+EGySz3+xI8Hk2g1T1KcLl7ytYxe3HE+C0vKYWvwL7k=,iv:phxrKPWW/5THQYRycQlo7CGvF/YNHS7WnxHS0bvwGHM=,tag:cqI4AC1BdqJyOKY3Mu1VaA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yefuafglgmxqztx50yt6ts2a2z9tg48ywnhgrz4zxlqh5w6xvqqqr22agq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpOUhVaGs0UmozVk5FdU56
            eFRoc3oxY3Rzajc1MTh4UmZCMG1LZmdFSFJRCk5GajBsQmJlWDBNd3hDNHN0MVg5
            eFhjbFViZnFNQ2VFRmNwOXAzUXZnZzgKLS0tIHZ5VjhKZURnb2RaaXZISnBXUWxh
            aWhjRitHdnYycG9JTjNLZWRSMWp2dzQKVB1VQ0qvZotzYPfrb49Uwr5Ap/X1FgaI
            B0tfboDcTy2LGa6doJKpJkHH9SKikiUPzx5aIZabr38jc1b6EWCfww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-31T20:00:57Z"
    mac: ENC[AES256_GCM,data:KSiYUq0ruY6CyycWtoCNHeGiYDVFKphYyzTqpN2yrW6ZJ/lUCKyYyB9PUk6e+StTtSB6VbhSYnzlA3ZyrPyMudYYKal8ibzLo4M/SQ7vs1UEOKnT37EVauLG1++XxyL9Ij6j+s9SCb4rovFcq27V6bQO6+dIzgDRU+BU7vkdE7A=,iv:/SiydaB+RbIn52ZRJBRTn/DNrT2kDPa9dUErid5Z0EY=,tag:BhTegzhVLf6pIo8wYgX4yA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
