---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-cluster
  namespace: database
spec:
  affinity:
    nodeSelector:
      kubernetes.io/arch: arm64
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16.2-10
  primaryUpdateStrategy: unsupervised
  storage:
    size: 20Gi
    storageClass: longhorn
  enableSuperuserAccess: true
  superuserSecret:
    name: cloudnative-pg-secrets
  postgresql:
    parameters:
      max_connections: "400"
      shared_buffers: 256MB
  # backup:
  #   retentionPolicy: 30d
  #   barmanObjectStore:
  #     wal:
  #       compression: bzip2
  #       maxParallel: 8
  #     destinationPath: &dest-path s3://cloudnative-pg/
  #     endpointURL: &endpoint-url http://minio.kube-system.svc.cluster.local:9000
  #     serverName: postgres-v13 #This must increment when bootstrapping. You cannot have this be the same as the bootstrap version
  #     s3Credentials: &s3-creds
  #       accessKeyId:
  #         name: cloudnative-pg-secrets
  #         key: AWS_ACCESS_KEY_ID
  #       secretAccessKey:
  #         name: cloudnative-pg-secrets
  #         key: AWS_SECRET_ACCESS_KEY
