# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./job.yaml
configMapGenerator:
  - name: cnpg-smoke-wal-sql
    files:
      - run.sql
      - wait-wal.sql
