---
kubernetes:
  children:
    controllers:
      hosts:
        "hcc":
          ansible_user: "root"
          ansible_host: "192.168.4.10"
        "hcc2":
          ansible_user: "root"
          ansible_host: "192.168.4.11"
        "hcc3":
          ansible_user: "hcc_admin"
          ansible_host: "192.168.4.13"
