# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - ./replicationdestination.yaml
patches:
  - target:
      kind: PersistentVolumeClaim
      labelSelector: volsync.home.arpa/restore=true
    patch: |-
      - op: add
        path: /spec/dataSourceRef
        value:
          apiGroup: volsync.backube
          kind: ReplicationDestination
          name: ${APP}-bootstrap-${VOLSYNC_RESTORE_ID}
