# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./mealie/ks.yaml
  - ./mealie/ks-database.yaml
  - ./mealie/ks-storage.yaml
  - ./mealie/ks-routes.yaml
