# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./k8s-explorer-eval/ks.yaml
  - ./k8s-explorer-eval/ks-storage.yaml
  - ./mealie/ks.yaml
  - ./mealie/ks-database.yaml
  - ./mealie/ks-storage.yaml
  - ./paperless/ks.yaml
  - ./paperless/ks-storage.yaml
  - ./paperless/ks-database.yaml
  - ./paperless/ks-broker.yaml
  - ./paperless/ks-sftp.yaml
  - ./paperless/ks-tailscale.yaml
  - ./paperless/ks-consume-monitor.yaml
  - ./teslamate/ks.yaml
  - ./teslamate/ks-database.yaml
  - ./home-assistant/ks.yaml
  - ./home-assistant/ks-storage.yaml
  - ./home-assistant/ks-database.yaml
  - ./home-assistant/ks-tailscale.yaml
  - ./node-red/ks.yaml
  - ./node-red/ks-storage.yaml
  - ./node-red/ks-tailscale.yaml
