# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret teslamate-postgres
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      data:
        username: teslamate
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: *secret
        property: password
