# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: []
patches:
  - target:
      group: postgresql.cnpg.io
      kind: Cluster
    patch: |-
      $patch: delete
      apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      metadata:
        name: unused
  - target:
      group: postgresql.cnpg.io
      kind: ScheduledBackup
    patch: |-
      $patch: delete
      apiVersion: postgresql.cnpg.io/v1
      kind: ScheduledBackup
      metadata:
        name: unused
