apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret
stringData:
    #ENC[AES256_GCM,data:wzo1YCJXMKIg,iv:6y+qP69JyLbqB8llweHcQc2+iihbVQUJYGzpowtXtcc=,tag:liq64PzFYf0T9Tc4NuYTDQ==,type:comment]
    AUTHENTIK_POSTGRESQL__USER: ENC[AES256_GCM,data:wMnqAqw3NYQO,iv:kSuy4PvDbmoG20BUO0c8mBVxmzYFspTeVF8iZga/Mhg=,tag:xlSIVnNy1QjsafgU9+4HNg==,type:str]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:jsxVH4RFAVunIaLVTLEhQWd2K8JvGxvU/V84exmn5UY=,iv:90YvsAi+NOAtQKlguJzTGYnSTuznVv5PNpiV/rUO9sY=,tag:9nmdpD49yEtpI4tmD853mQ==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:JRhEAXCyQFVh,iv:x4hgolXFTsiIMf3yM4C7+IzCvmmipDLr7VTA8U7YeHc=,tag:7C1dND24KXZ6W/MTqBT+1w==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:EuTpdSP2J+6N5w0xVFYAyNlDV4dJFnCf+5MwxPI0L6w=,iv:nbqnSHAPnHBRW0JVKzmhEQTJgB177Uy1Xu0LeBAtFAM=,tag:pRzFFp58Rn+Y7/DMH3iE4Q==,type:str]
    #ENC[AES256_GCM,data:7DG21p/We2ZTaw==,iv:JVcX/0iyafdTCN5dhECGBOcOePoFtcGKMsSAuKEhnwY=,tag:8dqKQPrRa4IR6/lC5oVTww==,type:comment]
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:JVcwmVhuxqQN4bWkmHY3GhgGO4Y/8Pr6oxLGFqW3Bk8rhQjEHtxMM7sluPt8pZYRG7A=,iv:m7sTQZmuv7jSHKSH+l6kwRo4uP00VuY/BJsIBkfM4a8=,tag:oVCsqzrzX8fDx52/NaLVVA==,type:str]
    #ENC[AES256_GCM,data:bzYiq9gL,iv:qb80nsjR6Ruu7d9QKON1l0h6gC2hHb0dpwtDT3yL5so=,tag:AW1d5PmSt6DdjpbC2JbjtA==,type:comment]
    AUTHENTIK_EMAIL__USERNAME: ENC[AES256_GCM,data:/ako/2fyqcZPXNQcv1kHMPsDmf0=,iv:zAyU9ADRA4GetWyToxBmqVgGbaJA9I3GN9e9aFCOYiA=,tag:8TkyUulQm/8WGvyz4mElnw==,type:str]
    AUTHENTIK_EMAIL__PASSWORD: ENC[AES256_GCM,data:h+x6SiSM8t9a3pK1vqsQBw==,iv:7KqxB9lhNo8QIqTgbnrrRFBHyMU+pgLcm7QKufk2a7k=,tag:hOQfwQcvqGTgIaNEd/bITg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yefuafglgmxqztx50yt6ts2a2z9tg48ywnhgrz4zxlqh5w6xvqqqr22agq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEbENRR1I1eFB2ZGNTWEZZ
            TUJudUNUeHU0VTNrU2o5eS9XZkdHRDVzWVZ3CjlKalJGT1hhWGx3bXAwUUJsVHRk
            ZWs0Z3liTzJ2QW8yK0VnSVRqVFcvRDQKLS0tIEtHejJOdGVaM0NxNzBuODBhSnM3
            YlZPTXZFQmhQVW00UTd4dnB2NjR2cVEKx/iE8/BCcRzdXZsUqd9IISSqOhaDrPcG
            MNm0tQx3NSxV3c8/+oAXeXIiUsL0d+X8cmLnQIZqHiApir0us51vgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-13T19:30:36Z"
    mac: ENC[AES256_GCM,data:s7eDYw62EaC4npm7hcwts5NbpNLryeI/WPMmZxt2KWF8mk7vWozfbkxv26WDRURMUci32uBfbxL4mjyRemWS97otig8yFG6IFc+dnKGKSMzY5Tzc/LekoElK9ZkJ8pr44UDmlL/eKpPh5mgVzeZ/SXhG+H8ojQVJKSlLWMWH6WI=,iv:vp/vuM7xNiTskAIqnFVjwbcVvw8KvGtXqLkHKsIX1i4=,tag:zdfEVIBUypQAQzCXR197Mw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
