# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.7.3/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: webfinger
  namespace: security
spec:
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: bjw-s
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  interval: 1h
  driftDetection:
    mode: enabled
  values:
    controllers:
      webfinger:
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: ghcr.io/evanmoelter/tailscale-authentik-webfinger
              tag: beta
              pullPolicy: Always
            env:
              TZ: ${TIMEZONE}
              AK_HOST: sso.${SECRET_DOMAIN}
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: [ALL]}
            probes:
              readiness: &probe
                enabled: true
                type: HTTP
                path: /ping
              liveness: *probe
              startup:
                <<: *probe
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
        pod:
          securityContext:
            runAsNonRoot: true
            seccompProfile: {type: RuntimeDefault}

    service:
      webfinger:
        controller: webfinger
        ports:
          http:
            port: 3000

    ingress:
      webfinger:
        enabled: true
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hosts:
          - host: &host "${SECRET_DOMAIN}"
            paths:
              - path: /.well-known/webfinger
                pathType: ImplementationSpecific
                service:
                  identifier: webfinger
                  port: http
        tls:
          - hosts:
              - *host
