# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app flux-operator-ui
  namespace: flux-system
spec:
  dependsOn:
    - name: flux-operator
    - name: envoy-gateway-config
  targetNamespace: flux-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apollo/apps/flux-system/flux-operator/ui
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 10m
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app flux-operator-tailscale
  namespace: flux-system
spec:
  dependsOn:
    - name: flux-operator
    - name: tailscale-config
  targetNamespace: flux-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apollo/apps/flux-system/flux-operator/tailscale
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  healthCheckExprs:
    - apiVersion: networking.k8s.io/v1
      kind: Ingress
      current: >-
        has(status.loadBalancer) && has(status.loadBalancer.ingress) &&
        status.loadBalancer.ingress.exists(e, has(e.hostname) && e.hostname != '')
  interval: 30m
  retryInterval: 1m
  timeout: 10m
