---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hubble-tailscale
  namespace: kube-system
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: hubble-ui
      port:
        name: http
  tls:
    - hosts:
        - hubble
