# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &app tailscale-operator
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: operator-oauth
    creationPolicy: Owner
  data:
    - secretKey: client_id
      remoteRef:
        key: *app
        property: client_id
    - secretKey: client_secret
      remoteRef:
        key: *app
        property: client_secret
