# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app mealie-cluster
  namespace: flux-system
spec:
  dependsOn:
    - name: plugin-barman-cloud
    - name: longhorn-config
    - name: onepassword-store
  targetNamespace: default
  path: ./kubernetes/apollo/apps/default/mealie/database
  components:
    - ../../../../components/postgres
  prune: true
  deletionPolicy: WaitForTermination
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  healthCheckExprs:
    - apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      current: >-
        has(status.conditions) &&
        status.conditions.exists(e, e.type == 'Ready' && e.status == 'True')
  interval: 30m
  retryInterval: 1m
  timeout: 30m
  postBuild:
    substitute:
      APP: mealie
      POSTGRES_IMAGE: ghcr.io/cloudnative-pg/postgresql:18.1-system-trixie@sha256:51bc94428be3df3e234447278e33803544a93d27a57a4b6af737f218d6472d12
