# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mealie-routes
  namespace: flux-system
spec:
  suspend: true
  dependsOn:
    - name: mealie
    - name: envoy-gateway-config
    - name: cloudflare-dns
    - name: unifi-dns
  targetNamespace: default
  path: ./kubernetes/apollo/apps/default/mealie/routes
  prune: true
  deletionPolicy: WaitForTermination
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  healthCheckExprs:
    - apiVersion: gateway.networking.k8s.io/v1
      kind: HTTPRoute
      current: >-
        has(status.parents) && status.parents.size() > 0 &&
        status.parents.all(p, has(p.conditions) &&
          p.conditions.exists(c, c.type == 'Accepted' && c.status == 'True' && c.observedGeneration == metadata.generation) &&
          p.conditions.exists(c, c.type == 'ResolvedRefs' && c.status == 'True' && c.observedGeneration == metadata.generation))
  interval: 30m
  retryInterval: 1m
  timeout: 10m
