apiVersion: v1
kind: Secret
metadata:
    name: mealie-secret
type: Opaque
stringData:
    #ENC[AES256_GCM,data:IAm5QeI=,iv:XsYGbVlBz7ErTPAHUrjpHyemARHHHCQwQz+ZqYpkWyA=,tag:70J1bCuEZCLFLRM1e9PhIA==,type:comment]
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:U3oeNVoQY2RZydnkdhpGGLke0mvE03XeOrQDG4KI1QtXV6f+6OCtpQ==,iv:O8bcwdlJGTrMfwczX0w/+SubK+rmZVCUMx1AIJjMQ/Y=,tag:Ly5eAwBLZ6f6wqUG1CDvQg==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:uc3o4V7HSt9+3sOZXTjgiU1hsmii6QzzYlXxH9z4yvXahJJb0FKqZWNj5SYbIyW5Ifqsq2IlgYKFPQpaE2DSAvmn+jYaKCWsT/pOOs0r6w1l7ZZS6RLJ+wABas10WV1cOWnZC+NzEe8w301AjXCD8hBpx1mHcwJzuA6Ct/PWlwc=,iv:Os1gA6Vzl0dILqvZFU5+/tTjI4xHr6bE/70HAUtovK8=,tag:nvMpe1r+58+ols59Z+fnWQ==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:6n8H4UTxfmBD3zC2SLyr0Mq8Eza/CRwMN+0lltmycjx1p0+XC81cZtPsWcgYG66NZsyqBG5YtCsiPuTn84Ien9lpqZtHIBxe4t2LG0cIAMaRRsB0o9HqosyEOGZvx+iZvD1SKM6ynluvlsymoM2Li2wXh3NElX16OlDwN4jVEVl2apj3vWPuD9j8QBe5ADUkgoOi9jyGjkQHe4zK70ZBBRW9zCOIgX8=,iv:a/xb27Dho8oxj+tZxZd/Cy3K6+dbzo0LVwVNuJBcrOs=,tag:Hc4Oa3JrARzhaVhVXkqpdw==,type:str]
    OPENAI_MODEL: ENC[AES256_GCM,data:hYSqq++0ljIp0flH,iv:4jbUQQABqW6iNNlG6MQQL7S6oZ6tQRhR+xZVFsjkmpk=,tag:Ah/cS0/aMSrOaK5nta4pxA==,type:str]
sops:
    age:
        - recipient: age1yefuafglgmxqztx50yt6ts2a2z9tg48ywnhgrz4zxlqh5w6xvqqqr22agq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxQXRSTUo4VmxLZy9scWo0
            VnZYUWJQL1pBQlJXb2VONmRsN1pYT3RreUh3CkQraHIwWTlSaWRyNTNjYnAvN3lR
            NTBvVW0wd3hKM2lUOFRDeHpNUTNESUkKLS0tIHk2SGwyTng5eFpBUzFCb0FMYmVl
            WHB4WGVHRkVBSTE1NG0wVnhndGllQncKE49BFWl4RflRIShDqVgrg87eY11F1F/N
            n6ey0hOVN+Iovn5ZgqcJP8xWmidksHKQZIFUUXeHx+iBeGfT7pTaJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T06:16:52Z"
    mac: ENC[AES256_GCM,data:PuisNUMH1a0hVz9avZWqrSvl3acRlLk1g4HDURUPs1upV7SzRtFEfzHbgkE3cE52xpc+hJwAgoHkMGrtoPbbnBvcoJ42uQN00O1t6RA8snEVW1PHEpAB6H0FwZrM1Dc3o+FxF9uhIEJDsCy1/PLyClroEUW135i72b8jSiDOyeE=,iv:FHoBlpth3Vie9wo/rf1An8mwZMJ5aIaHuafBSFb/vgI=,tag:TOLXAwMkJNgJepBPPoe9uA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: mealie-pg-r2
type: Opaque
stringData:
    R2_ACCESS_KEY_ID: ENC[AES256_GCM,data:mePO9h0vB/YVp3Ien9g3RFvqU1rdkLKZ1C7XwwZpoCU=,iv:kDZ/V5eSiGWI03wp9ZxH7tQirH9zX5cNigxMr4IYj7c=,tag:DQKsv/VgnKAYeWpU0yO3qg==,type:str]
    R2_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:X63RNXZF87ymXMJxlujGMcR1V6bjB5rP4TuFQJ/UJqFlIUplgRWwnVNVDAQ46d4eZTutN2ejKpLFep7GsF26GQ==,iv:5yrJ5T7+07WibPWtEqsEWMzAy8guuFPvqbECBEofgsM=,tag:A2S/w3V0PtcG2tAPfFrIyg==,type:str]
sops:
    age:
        - recipient: age1yefuafglgmxqztx50yt6ts2a2z9tg48ywnhgrz4zxlqh5w6xvqqqr22agq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxQXRSTUo4VmxLZy9scWo0
            VnZYUWJQL1pBQlJXb2VONmRsN1pYT3RreUh3CkQraHIwWTlSaWRyNTNjYnAvN3lR
            NTBvVW0wd3hKM2lUOFRDeHpNUTNESUkKLS0tIHk2SGwyTng5eFpBUzFCb0FMYmVl
            WHB4WGVHRkVBSTE1NG0wVnhndGllQncKE49BFWl4RflRIShDqVgrg87eY11F1F/N
            n6ey0hOVN+Iovn5ZgqcJP8xWmidksHKQZIFUUXeHx+iBeGfT7pTaJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T06:16:52Z"
    mac: ENC[AES256_GCM,data:PuisNUMH1a0hVz9avZWqrSvl3acRlLk1g4HDURUPs1upV7SzRtFEfzHbgkE3cE52xpc+hJwAgoHkMGrtoPbbnBvcoJ42uQN00O1t6RA8snEVW1PHEpAB6H0FwZrM1Dc3o+FxF9uhIEJDsCy1/PLyClroEUW135i72b8jSiDOyeE=,iv:FHoBlpth3Vie9wo/rf1An8mwZMJ5aIaHuafBSFb/vgI=,tag:TOLXAwMkJNgJepBPPoe9uA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
