---
apiVersion: v1
kind: Secret
metadata:
  name: mealie-secret
type: Opaque
stringData:
  # OIDC
  OIDC_CLIENT_ID: REPLACE_ME
  OIDC_CLIENT_SECRET: REPLACE_ME
---
apiVersion: v1
kind: Secret
metadata:
  name: mealie-pg-r2
type: Opaque
stringData:
  R2_ACCESS_KEY_ID: REPLACE_ME
  R2_SECRET_ACCESS_KEY: REPLACE_ME
