apiVersion: v1
kind: Secret
metadata:
    name: mealie-secret
type: Opaque
stringData:
    #ENC[AES256_GCM,data:IAm5QeI=,iv:XsYGbVlBz7ErTPAHUrjpHyemARHHHCQwQz+ZqYpkWyA=,tag:70J1bCuEZCLFLRM1e9PhIA==,type:comment]
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:U3oeNVoQY2RZydnkdhpGGLke0mvE03XeOrQDG4KI1QtXV6f+6OCtpQ==,iv:O8bcwdlJGTrMfwczX0w/+SubK+rmZVCUMx1AIJjMQ/Y=,tag:Ly5eAwBLZ6f6wqUG1CDvQg==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:uc3o4V7HSt9+3sOZXTjgiU1hsmii6QzzYlXxH9z4yvXahJJb0FKqZWNj5SYbIyW5Ifqsq2IlgYKFPQpaE2DSAvmn+jYaKCWsT/pOOs0r6w1l7ZZS6RLJ+wABas10WV1cOWnZC+NzEe8w301AjXCD8hBpx1mHcwJzuA6Ct/PWlwc=,iv:Os1gA6Vzl0dILqvZFU5+/tTjI4xHr6bE/70HAUtovK8=,tag:nvMpe1r+58+ols59Z+fnWQ==,type:str]
sops:
    age:
        - recipient: age1yefuafglgmxqztx50yt6ts2a2z9tg48ywnhgrz4zxlqh5w6xvqqqr22agq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxQXRSTUo4VmxLZy9scWo0
            VnZYUWJQL1pBQlJXb2VONmRsN1pYT3RreUh3CkQraHIwWTlSaWRyNTNjYnAvN3lR
            NTBvVW0wd3hKM2lUOFRDeHpNUTNESUkKLS0tIHk2SGwyTng5eFpBUzFCb0FMYmVl
            WHB4WGVHRkVBSTE1NG0wVnhndGllQncKE49BFWl4RflRIShDqVgrg87eY11F1F/N
            n6ey0hOVN+Iovn5ZgqcJP8xWmidksHKQZIFUUXeHx+iBeGfT7pTaJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-18T04:37:07Z"
    mac: ENC[AES256_GCM,data:/ajGi5pgOXeYR9e66I5RZ4OVEdfVuYr7Q1aUTN+XyzJ1Vn1tXOB42Was+/gpCt9niZ4hpLrw8wifd/UqXlrGdKQi6eXyq6h2iyZDsXDw2Q5uqKkkg2udFoqsMLp2oGEuKakdVu+sTyFV//wFsGcc1uyfGYOihmi15cPpCB15XC0=,iv:k/chD4+1wnI/LTIdzntIbPVlxtA35E8PLyHtu5TXbxM=,tag:TxHu/gss4dWJBQdZTzmSOQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: mealie-pg-r2
type: Opaque
stringData:
    R2_ACCESS_KEY_ID: ENC[AES256_GCM,data:mePO9h0vB/YVp3Ien9g3RFvqU1rdkLKZ1C7XwwZpoCU=,iv:kDZ/V5eSiGWI03wp9ZxH7tQirH9zX5cNigxMr4IYj7c=,tag:DQKsv/VgnKAYeWpU0yO3qg==,type:str]
    R2_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:X63RNXZF87ymXMJxlujGMcR1V6bjB5rP4TuFQJ/UJqFlIUplgRWwnVNVDAQ46d4eZTutN2ejKpLFep7GsF26GQ==,iv:5yrJ5T7+07WibPWtEqsEWMzAy8guuFPvqbECBEofgsM=,tag:A2S/w3V0PtcG2tAPfFrIyg==,type:str]
sops:
    age:
        - recipient: age1yefuafglgmxqztx50yt6ts2a2z9tg48ywnhgrz4zxlqh5w6xvqqqr22agq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxQXRSTUo4VmxLZy9scWo0
            VnZYUWJQL1pBQlJXb2VONmRsN1pYT3RreUh3CkQraHIwWTlSaWRyNTNjYnAvN3lR
            NTBvVW0wd3hKM2lUOFRDeHpNUTNESUkKLS0tIHk2SGwyTng5eFpBUzFCb0FMYmVl
            WHB4WGVHRkVBSTE1NG0wVnhndGllQncKE49BFWl4RflRIShDqVgrg87eY11F1F/N
            n6ey0hOVN+Iovn5ZgqcJP8xWmidksHKQZIFUUXeHx+iBeGfT7pTaJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-18T04:37:07Z"
    mac: ENC[AES256_GCM,data:/ajGi5pgOXeYR9e66I5RZ4OVEdfVuYr7Q1aUTN+XyzJ1Vn1tXOB42Was+/gpCt9niZ4hpLrw8wifd/UqXlrGdKQi6eXyq6h2iyZDsXDw2Q5uqKkkg2udFoqsMLp2oGEuKakdVu+sTyFV//wFsGcc1uyfGYOihmi15cPpCB15XC0=,iv:k/chD4+1wnI/LTIdzntIbPVlxtA35E8PLyHtu5TXbxM=,tag:TxHu/gss4dWJBQdZTzmSOQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
