# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gatus
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: gatus-secret
    creationPolicy: Owner
  data:
    - secretKey: PUSHOVER_USER_KEY
      remoteRef:
        key: pushover
        property: PUSHOVER_USER_KEY
    - secretKey: PUSHOVER_API_TOKEN
      remoteRef:
        key: pushover
        property: PUSHOVER_API_TOKEN
