---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "America/Los_Angeles"
  CLUSTER_CIDR: "10.69.0.0/16"
  NODE_CIDR: "192.168.4.0/22"
  LB_K8S_GATEWAY: "192.168.5.15"
  LB_PIHOLE: "192.168.5.53"
  CNPG_CLUSTER_HOST: "cnpg-cluster-rw.database.svc.cluster.local"
