---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app capacitor
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false

  values:
    controllers:
      capacitor:
        strategy: RollingUpdate

        containers:
          app:
            env:
              TZ: ${TIMEZONE}
            image:
              repository: ghcr.io/gimlet-io/capacitor
              tag: v0.4.8@sha256:c999a42cccc523b91086547f890466d09be4755bf05a52763b0d14594bf60782
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: [ALL]}

    serviceAccount:
      create: true
      name: "capacitor"

    rbac:
      roles:
        capacitor-role:
          type: ClusterRole
          rules:
          - apiGroups:
              - networking.k8s.io
              - apps
              - ""
            resources:
              - pods
              - pods/log
              - ingresses
              - deployments
              - services
              - secrets
              - events
              - configmaps
            verbs:
              - get
              - watch
              - list
          - apiGroups:
              - source.toolkit.fluxcd.io
              - kustomize.toolkit.fluxcd.io
              - helm.toolkit.fluxcd.io
              - infra.contrib.fluxcd.io
            resources:
              - gitrepositories
              - ocirepositories
              - buckets
              - helmrepositories
              - helmcharts
              - kustomizations
              - helmreleases
              - terraforms
            verbs:
              - get
              - watch
              - list
              - patch # to allow force reconciling by adding an annotation

      bindings:
        capacitor-binding:
          type: ClusterRoleBinding
          roleRef:
            identifier: capacitor-role
          subjects:
            - identifier: capacitor

    service:
      app:
        controller: capacitor
        ports:
          http:
            enabled: true
            port: 9000

    ingress:
      app:
        enabled: true
        className: internal
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
