# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./longhorn/ks.yaml
  - ./longhorn/ks-config.yaml
  - ./snapshot-controller/ks.yaml
  - ./snapshot-controller/ks-config.yaml
  - ./volsync/ks.yaml
  - ./volsync-test/ks.yaml
  - ./volsync-test/ks-storage.yaml
  - ./volsync-test/ks-fixture.yaml
