# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      data:
        PAPERLESS_SECRET_KEY: "{{ .secret_key }}"
        PAPERLESS_SOCIALACCOUNT_PROVIDERS: "{{ .providers }}"
        PAPERLESS_REDIS: 'redis://:{{ .password | urlquery | replace "+" "%20" }}@paperless-dragonfly.default.svc.cluster.local:6379/0'
  data:
    - secretKey: secret_key
      remoteRef:
        key: paperless
        property: PAPERLESS_SECRET_KEY
    - secretKey: providers
      remoteRef:
        key: paperless
        property: PAPERLESS_SOCIALACCOUNT_PROVIDERS
    - secretKey: password
      remoteRef:
        key: paperless-dragonfly
        property: password
