---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: "paperless-library-r2"
spec:
  sourcePVC: paperless-library
  trigger:
    schedule: "9 0 * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 7
    repository: "paperless-library-volsync-r2"
    volumeSnapshotClassName: longhorn-snapclass
    cacheCapacity: "8Gi"
    cacheStorageClassName: longhorn-cache
    cacheAccessModes: ["ReadWriteOnce"]
    storageClassName: longhorn-snapshot
    accessModes: ["ReadWriteOnce"]
    moverSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
    retain:
      daily: 7
      weekly: 6
      monthly: 12
      yearly: 1
