---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-library
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-consume
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
