# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: multus
spec:
  interval: 1h
  url: oci://ghcr.io/home-operations/charts/multus
  ref:
    tag: 0.1.0
    digest: sha256:554367a617b08f2ba6d9f1c5b43001acd8a8c79fe274df286c042280bf67f9e1
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
