# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app tailscale-config
  namespace: flux-system
spec:
  dependsOn:
    - name: tailscale-operator
  targetNamespace: network
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apollo/apps/network/tailscale/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  healthCheckExprs:
    - apiVersion: tailscale.com/v1alpha1
      kind: ProxyClass
      current: status.conditions.exists(e, e.type == 'ProxyClassReady' && e.status == 'True')
  interval: 30m
  retryInterval: 1m
  timeout: 10m
