# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn-recovery-nodes
  namespace: flux-system
spec:
  dependsOn:
    - name: longhorn
  targetNamespace: storage
  path: ./kubernetes/main/apps/storage/longhorn/recovery
  prune: false
  deletionPolicy: Orphan
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
