# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app cert-manager-secrets
  namespace: flux-system
spec:
  dependsOn:
    - name: onepassword-store
  targetNamespace: security
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apollo/apps/security/cert-manager/secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  healthCheckExprs:
    - apiVersion: external-secrets.io/v1
      kind: ExternalSecret
      current: status.conditions.exists(e, e.type == 'Ready' && e.status == 'True')
  interval: 30m
  retryInterval: 1m
  timeout: 10m
