# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: volsync-test-preflight
  namespace: flux-system
spec:
  dependsOn:
    - name: volsync-test-backup
    - name: onepassword-store
  targetNamespace: storage
  path: ./kubernetes/apollo/apps/storage/volsync-test/preflight
  components:
    - ../../../../components/volsync/restore-preflight
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 20m
  postBuild:
    substitute:
      APP: volsync-test
      VOLSYNC_RESTORE_ID: "v1"
      VOLSYNC_RESTORE_BUCKET: "tf-hcc-apollo-volsync"
