# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: volsync-test-verify
  namespace: flux-system
spec:
  dependsOn:
    - name: volsync-test-restore
  targetNamespace: storage
  path: ./kubernetes/apollo/apps/storage/volsync-test/verify
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
