# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: authentik
spec:
  interval: 1h
  url: oci://ghcr.io/goauthentik/helm-charts/authentik
  ref:
    tag: 2025.12.4
    digest: sha256:fe6bccbcfd43fb8fdadc14a2ceaadade6394f52dbc134af6b40bb4c391c5ef3c
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
