# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: authentik
spec:
  interval: 1h
  url: oci://ghcr.io/goauthentik/helm-charts/authentik
  ref:
    tag: 2026.2.3
    digest: sha256:1b98a4c8520c29d18cfaea06d501fab71e713dc5030f12132966fc41291f7f8f
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
