# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./cloudnative-pg/ks.yaml
  - ./cloudnative-pg/ks-barman.yaml
  - ./cnpg-smoke/ks-cluster.yaml
  - ./cnpg-smoke/ks-backup.yaml
  - ./cnpg-smoke/ks-seed.yaml
