---
apiVersion: v1
kind: Pod
metadata:
  name: backup-pod
spec:
  containers:
  - name: temp-container
    image: busybox
    command: ["sleep", "36000"]
    volumeMounts:
    - name: backup-volume
      mountPath: /backup
  volumes:
  - name: backup-volume
    persistentVolumeClaim:
      claimName: teslamate-backup-pvc
