# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mealie-pg-source-r2
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ENDPOINT_URL: "https://{{ .ACCOUNT_ID }}.r2.cloudflarestorage.com"
        R2_ACCESS_KEY_ID: "{{ .R2_ACCESS_KEY_ID }}"
        R2_SECRET_ACCESS_KEY: "{{ .R2_SECRET_ACCESS_KEY }}"
  data:
    - secretKey: ACCOUNT_ID
      remoteRef:
        key: cloudflare-r2
        property: ACCOUNT_ID
    - secretKey: R2_ACCESS_KEY_ID
      remoteRef:
        key: &item mealie-postgres-migration
        property: R2_ACCESS_KEY_ID
    - secretKey: R2_SECRET_ACCESS_KEY
      remoteRef:
        key: *item
        property: R2_SECRET_ACCESS_KEY
