# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/barmancloud.cnpg.io/objectstore_v1.json
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: mealie-pg-source
spec:
  configuration:
    destinationPath: s3://tf-hcc-cloudnativepg/
    s3Credentials:
      accessKeyId:
        name: &secret mealie-pg-source-r2
        key: R2_ACCESS_KEY_ID
      secretAccessKey:
        name: *secret
        key: R2_SECRET_ACCESS_KEY
    data:
      compression: bzip2
    wal:
      compression: bzip2
      maxParallel: 4
  instanceSidecarConfiguration:
    env:
      - name: AWS_ENDPOINT_URL_S3
        valueFrom:
          secretKeyRef:
            name: *secret
            key: ENDPOINT_URL
