# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./envoy-gateway/ks.yaml
  - ./envoy-gateway/ks-certificates.yaml
  - ./envoy-gateway/ks-config.yaml
  - ./echo-server/ks.yaml
