# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflared
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: cloudflared-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      mergePolicy: Merge
      data:
        TUNNEL_ID: '{{ (index . "credentials.json" | fromJson).TunnelID }}'
  data:
    - secretKey: credentials.json
      remoteRef:
        key: cloudflared
        property: credentials.json
