# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ${APP}-volsync-restore-${VOLSYNC_RESTORE_ID}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: ${APP}-volsync-restore-${VOLSYNC_RESTORE_ID}
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        RESTIC_REPOSITORY: "s3:https://{{ .R2_ACCOUNT_ID }}.r2.cloudflarestorage.com/${VOLSYNC_RESTORE_BUCKET}/${VOLSYNC_RESTORE_PATH:-${APP}}"
        RESTIC_PASSWORD: "{{ .RESTIC_PASSWORD }}"
        AWS_ACCESS_KEY_ID: "{{ .AWS_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .AWS_SECRET_ACCESS_KEY }}"
        AWS_DEFAULT_REGION: auto
  data:
    - secretKey: R2_ACCOUNT_ID
      remoteRef:
        key: cloudflare-r2
        property: ACCOUNT_ID
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: &item ${VOLSYNC_RESTORE_CREDENTIALS_ITEM:-${APP}}
        property: AWS_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: *item
        property: AWS_SECRET_ACCESS_KEY
    - secretKey: RESTIC_PASSWORD
      remoteRef:
        key: *item
        property: RESTIC_PASSWORD
