# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./job.yaml
configMapGenerator:
  - name: volsync-test-seed
    files:
      - seed.py
patches:
  - target:
      kind: PersistentVolumeClaim
    patch: |-
      - op: remove
        path: /metadata/annotations/kustomize.toolkit.fluxcd.io~1prune
