---
apiVersion: v1
kind: ConfigMap
metadata:
  name: scanner-sshd-config
data:
  scanner-sshd-config: |
    # Add these configs to support Brother Scanner
    KexAlgorithms +diffie-hellman-group14-sha1
    HostKeyAlgorithms +ssh-rsa
    PubkeyAcceptedKeyTypes +ssh-rsa
