# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - target:
      group: postgresql.cnpg.io
      kind: Cluster
    patch: |-
      - op: replace
        path: /spec/bootstrap
        value:
          initdb:
            database: ${POSTGRES_DATABASE:-${APP}}
            owner: ${POSTGRES_USERNAME:-${APP}}
      - op: remove
        path: /spec/externalClusters
      - op: remove
        path: /metadata/annotations/cnpg.io~1skipEmptyWalArchiveCheck
