# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./hcc5.yaml
  - ./hcc6.yaml
  - ./hcc7.yaml
  - ./storageclass.yaml
